spring:
  datasource:
    primary:
      url: jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
    log:
      url: jdbc:postgresql://localhost:5432/pet_log
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
